// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockServices creates a new instance of MockServices. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServices(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServices {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockServices{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockServices is an autogenerated mock type for the Services type
type MockServices struct {
	mock.Mock
}

type MockServices_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServices) EXPECT() *MockServices_Expecter {
	return &MockServices_Expecter{mock: &_m.Mock}
}

// LockKey provides a mock function for the type MockServices
func (_mock *MockServices) LockKey() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LockKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockServices_LockKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockKey'
type MockServices_LockKey_Call struct {
	*mock.Call
}

// LockKey is a helper method to define mock.On call
func (_e *MockServices_Expecter) LockKey() *MockServices_LockKey_Call {
	return &MockServices_LockKey_Call{Call: _e.mock.On("LockKey")}
}

func (_c *MockServices_LockKey_Call) Run(run func()) *MockServices_LockKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServices_LockKey_Call) Return(s string) *MockServices_LockKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockServices_LockKey_Call) RunAndReturn(run func() string) *MockServices_LockKey_Call {
	_c.Call.Return(run)
	return _c
}

// Running provides a mock function for the type MockServices
func (_mock *MockServices) Running(ctx context.Context, requested []string) ([]string, error) {
	ret := _mock.Called(ctx, requested)

	if len(ret) == 0 {
		panic("no return value specified for Running")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]string, error)); ok {
		return returnFunc(ctx, requested)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = returnFunc(ctx, requested)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, requested)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServices_Running_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Running'
type MockServices_Running_Call struct {
	*mock.Call
}

// Running is a helper method to define mock.On call
//   - ctx context.Context
//   - requested []string
func (_e *MockServices_Expecter) Running(ctx any, requested any) *MockServices_Running_Call {
	return &MockServices_Running_Call{Call: _e.mock.On("Running", ctx, requested)}
}

func (_c *MockServices_Running_Call) Run(run func(ctx context.Context, requested []string)) *MockServices_Running_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServices_Running_Call) Return(strings []string, err error) *MockServices_Running_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockServices_Running_Call) RunAndReturn(run func(ctx context.Context, requested []string) ([]string, error)) *MockServices_Running_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockServices
func (_mock *MockServices) Start(ctx context.Context, services []string, timeout time.Duration) (bool, error) {
	ret := _mock.Called(ctx, services, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, time.Duration) (bool, error)); ok {
		return returnFunc(ctx, services, timeout)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, time.Duration) bool); ok {
		r0 = returnFunc(ctx, services, timeout)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, time.Duration) error); ok {
		r1 = returnFunc(ctx, services, timeout)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServices_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockServices_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - services []string
//   - timeout time.Duration
func (_e *MockServices_Expecter) Start(ctx any, services any, timeout any) *MockServices_Start_Call {
	return &MockServices_Start_Call{Call: _e.mock.On("Start", ctx, services, timeout)}
}

func (_c *MockServices_Start_Call) Run(run func(ctx context.Context, services []string, timeout time.Duration)) *MockServices_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServices_Start_Call) Return(b bool, err error) *MockServices_Start_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockServices_Start_Call) RunAndReturn(run func(ctx context.Context, services []string, timeout time.Duration) (bool, error)) *MockServices_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockServices
func (_mock *MockServices) Stop(ctx context.Context, services []string, timeout time.Duration) (bool, error) {
	ret := _mock.Called(ctx, services, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, time.Duration) (bool, error)); ok {
		return returnFunc(ctx, services, timeout)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, time.Duration) bool); ok {
		r0 = returnFunc(ctx, services, timeout)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, time.Duration) error); ok {
		r1 = returnFunc(ctx, services, timeout)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServices_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockServices_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - services []string
//   - timeout time.Duration
func (_e *MockServices_Expecter) Stop(ctx any, services any, timeout any) *MockServices_Stop_Call {
	return &MockServices_Stop_Call{Call: _e.mock.On("Stop", ctx, services, timeout)}
}

func (_c *MockServices_Stop_Call) Run(run func(ctx context.Context, services []string, timeout time.Duration)) *MockServices_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServices_Stop_Call) Return(b bool, err error) *MockServices_Stop_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockServices_Stop_Call) RunAndReturn(run func(ctx context.Context, services []string, timeout time.Duration) (bool, error)) *MockServices_Stop_Call {
	_c.Call.Return(run)
	return _c
}
