// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockLocker creates a new instance of MockLocker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocker {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockLocker{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockLocker is an autogenerated mock type for the Locker type
type MockLocker struct {
	mock.Mock
}

type MockLocker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocker) EXPECT() *MockLocker_Expecter {
	return &MockLocker_Expecter{mock: &_m.Mock}
}

// CleanupStale provides a mock function for the type MockLocker
func (_mock *MockLocker) CleanupStale() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CleanupStale")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLocker_CleanupStale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupStale'
type MockLocker_CleanupStale_Call struct {
	*mock.Call
}

// CleanupStale is a helper method to define mock.On call
func (_e *MockLocker_Expecter) CleanupStale() *MockLocker_CleanupStale_Call {
	return &MockLocker_CleanupStale_Call{Call: _e.mock.On("CleanupStale")}
}

func (_c *MockLocker_CleanupStale_Call) Run(run func()) *MockLocker_CleanupStale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLocker_CleanupStale_Call) Return(err error) *MockLocker_CleanupStale_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLocker_CleanupStale_Call) RunAndReturn(run func() error) *MockLocker_CleanupStale_Call {
	_c.Call.Return(run)
	return _c
}

// Lock provides a mock function for the type MockLocker
func (_mock *MockLocker) Lock(key string) (func() error, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 func() error
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (func() error, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) func() error); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func() error)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLocker_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type MockLocker_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - key string
func (_e *MockLocker_Expecter) Lock(key any) *MockLocker_Lock_Call {
	return &MockLocker_Lock_Call{Call: _e.mock.On("Lock", key)}
}

func (_c *MockLocker_Lock_Call) Run(run func(key string)) *MockLocker_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLocker_Lock_Call) Return(release func() error, err error) *MockLocker_Lock_Call {
	_c.Call.Return(release, err)
	return _c
}

func (_c *MockLocker_Lock_Call) RunAndReturn(run func(key string) (func() error, error)) *MockLocker_Lock_Call {
	_c.Call.Return(run)
	return _c
}
