// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRestic creates a new instance of MockRestic. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestic(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestic {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRestic{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRestic is an autogenerated mock type for the Restic type
type MockRestic struct {
	mock.Mock
}

type MockRestic_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestic) EXPECT() *MockRestic_Expecter {
	return &MockRestic_Expecter{mock: &_m.Mock}
}

// Backup provides a mock function for the type MockRestic
func (_mock *MockRestic) Backup(ctx context.Context, tag string, sources []string, opts []string) (string, error) {
	ret := _mock.Called(ctx, tag, sources, opts)

	if len(ret) == 0 {
		panic("no return value specified for Backup")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, []string) (string, error)); ok {
		return returnFunc(ctx, tag, sources, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, []string) string); ok {
		r0 = returnFunc(ctx, tag, sources, opts)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string, []string) error); ok {
		r1 = returnFunc(ctx, tag, sources, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestic_Backup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backup'
type MockRestic_Backup_Call struct {
	*mock.Call
}

// Backup is a helper method to define mock.On call
//   - ctx context.Context
//   - tag string
//   - sources []string
//   - opts []string
func (_e *MockRestic_Expecter) Backup(ctx any, tag any, sources any, opts any) *MockRestic_Backup_Call {
	return &MockRestic_Backup_Call{Call: _e.mock.On("Backup", ctx, tag, sources, opts)}
}

func (_c *MockRestic_Backup_Call) Run(run func(ctx context.Context, tag string, sources []string, opts []string)) *MockRestic_Backup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRestic_Backup_Call) Return(s string, err error) *MockRestic_Backup_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRestic_Backup_Call) RunAndReturn(run func(ctx context.Context, tag string, sources []string, opts []string) (string, error)) *MockRestic_Backup_Call {
	_c.Call.Return(run)
	return _c
}

// Forget provides a mock function for the type MockRestic
func (_mock *MockRestic) Forget(ctx context.Context, tag string, policy string, opts []string) error {
	ret := _mock.Called(ctx, tag, policy, opts)

	if len(ret) == 0 {
		panic("no return value specified for Forget")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) error); ok {
		r0 = returnFunc(ctx, tag, policy, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRestic_Forget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forget'
type MockRestic_Forget_Call struct {
	*mock.Call
}

// Forget is a helper method to define mock.On call
//   - ctx context.Context
//   - tag string
//   - policy string
//   - opts []string
func (_e *MockRestic_Expecter) Forget(ctx any, tag any, policy any, opts any) *MockRestic_Forget_Call {
	return &MockRestic_Forget_Call{Call: _e.mock.On("Forget", ctx, tag, policy, opts)}
}

func (_c *MockRestic_Forget_Call) Run(run func(ctx context.Context, tag string, policy string, opts []string)) *MockRestic_Forget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRestic_Forget_Call) Return(err error) *MockRestic_Forget_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRestic_Forget_Call) RunAndReturn(run func(ctx context.Context, tag string, policy string, opts []string) error) *MockRestic_Forget_Call {
	_c.Call.Return(run)
	return _c
}

// Prune provides a mock function for the type MockRestic
func (_mock *MockRestic) Prune(ctx context.Context, opts []string) error {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRestic_Prune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prune'
type MockRestic_Prune_Call struct {
	*mock.Call
}

// Prune is a helper method to define mock.On call
//   - ctx context.Context
//   - opts []string
func (_e *MockRestic_Expecter) Prune(ctx any, opts any) *MockRestic_Prune_Call {
	return &MockRestic_Prune_Call{Call: _e.mock.On("Prune", ctx, opts)}
}

func (_c *MockRestic_Prune_Call) Run(run func(ctx context.Context, opts []string)) *MockRestic_Prune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestic_Prune_Call) Return(err error) *MockRestic_Prune_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRestic_Prune_Call) RunAndReturn(run func(ctx context.Context, opts []string) error) *MockRestic_Prune_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function for the type MockRestic
func (_mock *MockRestic) Unlock(ctx context.Context, opts []string) error {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRestic_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type MockRestic_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - ctx context.Context
//   - opts []string
func (_e *MockRestic_Expecter) Unlock(ctx any, opts any) *MockRestic_Unlock_Call {
	return &MockRestic_Unlock_Call{Call: _e.mock.On("Unlock", ctx, opts)}
}

func (_c *MockRestic_Unlock_Call) Run(run func(ctx context.Context, opts []string)) *MockRestic_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestic_Unlock_Call) Return(err error) *MockRestic_Unlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRestic_Unlock_Call) RunAndReturn(run func(ctx context.Context, opts []string) error) *MockRestic_Unlock_Call {
	_c.Call.Return(run)
	return _c
}
