version: 2

project_name: dbk
before:
  hooks:
    - go mod tidy
    - go fmt ./...

builds:
  - id: solis-multi-arch
    main: ./main.go
    binary: dbk
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goamd64:
      - v3
    goarm:
      - 7
    goarm64:
      - v8.0
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X github.com/dombyte/dbk/cmd.Version={{.Version}} -X github.com/dombyte/dbk/cmd.BuildDate={{.Date}} -X github.com/dombyte/dbk/cmd.GitCommit={{.ShortCommit}}"
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
          - LICENSE
          - README.md

changelog:
  sort: asc
  use: github
  format: |
    {{ .Message -}}
        {{- if .Logins }} by {{ .Logins | englishJoin }}{{- end -}}
        {{- if .SHA }}
          {{- $sha := split .SHA "" -}}
          {{- if .Logins }} in {{ else }} in {{ end }}[#{{ index $sha 0 }}{{ index $sha 1 }}{{ index $sha 2 }}{{ index $sha 3 }}{{ index $sha 4 }}{{ index $sha 5 }}{{ index $sha 6 }}]({{ .GitURL }}/commit/{{ .SHA }})
        {{- end }}
  filters:
    exclude:
      - "^test: "
      - "^chore:"
      - "Merge branch"
      - "Merge pull request"
      - "^test:"
      - "^rebase:"

release:
  name_template: "v{{.Version}}"
  prerelease: auto
  header: |
    {{- if .Prerelease }}
    > [!WARNING]
    > **This is a pre-release version. Use with caution and report any issues you encounter.**

    **{{.TagContents}}**
    {{ else }}
    {{.ProjectName}} v{{.Version}} is available!

    **{{.TagContents}}**
    {{- end }}

  footer: |
    {{- if and .PreviousTag .Tag -}}
    **Full Changelog**: [{{ .PreviousTag }}...{{ .Tag }}]({{ .GitURL }}/compare/{{ .PreviousTag }}...{{ .Tag }})
    {{- end -}}




checksum:
  name_template: "checksums.txt"
