// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockProcesses creates a new instance of MockProcesses. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcesses(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcesses {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockProcesses{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockProcesses is an autogenerated mock type for the Processes type
type MockProcesses struct {
	mock.Mock
}

type MockProcesses_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcesses) EXPECT() *MockProcesses_Expecter {
	return &MockProcesses_Expecter{mock: &_m.Mock}
}

// Alive provides a mock function for the type MockProcesses
func (_mock *MockProcesses) Alive(pid int) bool {
	ret := _mock.Called(pid)

	if len(ret) == 0 {
		panic("no return value specified for Alive")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int) bool); ok {
		r0 = returnFunc(pid)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProcesses_Alive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Alive'
type MockProcesses_Alive_Call struct {
	*mock.Call
}

// Alive is a helper method to define mock.On call
//   - pid int
func (_e *MockProcesses_Expecter) Alive(pid any) *MockProcesses_Alive_Call {
	return &MockProcesses_Alive_Call{Call: _e.mock.On("Alive", pid)}
}

func (_c *MockProcesses_Alive_Call) Run(run func(pid int)) *MockProcesses_Alive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProcesses_Alive_Call) Return(b bool) *MockProcesses_Alive_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProcesses_Alive_Call) RunAndReturn(run func(pid int) bool) *MockProcesses_Alive_Call {
	_c.Call.Return(run)
	return _c
}
